#include "crypto/KeyManager.h"
#include "core/Logger.h"

#include <fcntl.h>
#include <unistd.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <stdexcept>

namespace bsfchat::id {

KeyManager::KeyManager(const std::string& keys_path) {
    load_or_generate(keys_path);
}

void KeyManager::load_or_generate(const std::string& keys_path) {
    namespace fs = std::filesystem;
    auto log = get_logger();

    fs::create_directories(keys_path);

    auto priv_path = fs::path(keys_path) / "private.pem";
    auto pub_path = fs::path(keys_path) / "public.pem";

    if (fs::exists(priv_path) && fs::exists(pub_path)) {
        log->info("Loading existing RSA keys from {}", keys_path);

        auto read_file = [](const fs::path& p) -> std::string {
            std::ifstream f(p);
            if (!f) throw std::runtime_error("Failed to read key file: " + p.string());
            std::ostringstream ss;
            ss << f.rdbuf();
            return ss.str();
        };

        private_key_pem_ = read_file(priv_path);
        public_key_pem_ = read_file(pub_path);

        // Keys generated by older builds were written with the umask.
        std::error_code ec;
        auto perms = fs::status(priv_path, ec).permissions();
        if (!ec && (perms & (fs::perms::group_all | fs::perms::others_all)) != fs::perms::none) {
            fs::permissions(priv_path, fs::perms::owner_read | fs::perms::owner_write,
                            fs::perm_options::replace, ec);
            if (ec) {
                log->warn("{} is readable by group/others and could not be tightened: {}",
                          priv_path.string(), ec.message());
            } else {
                log->info("Tightened permissions on {} to 0600", priv_path.string());
            }
        }
    } else {
        log->info("Generating new RSA keypair in {}", keys_path);

        auto [priv, pub] = bsfchat::generate_rsa_keypair();
        private_key_pem_ = priv;
        public_key_pem_ = pub;

        // Save keys to files. The private key is created 0600 rather than
        // with the process umask (normally 0644): whoever can read it can sign
        // an id_token for any account (security audit L5). O_EXCL so a file
        // planted at the path in the meantime is not written through.
        {
            int fd = ::open(priv_path.c_str(), O_WRONLY | O_CREAT | O_EXCL | O_TRUNC, 0600);
            if (fd < 0) throw std::runtime_error("Failed to write private key");
            const char* data = private_key_pem_.data();
            size_t left = private_key_pem_.size();
            while (left > 0) {
                auto n = ::write(fd, data, left);
                if (n <= 0) {
                    ::close(fd);
                    throw std::runtime_error("Failed to write private key");
                }
                data += n;
                left -= static_cast<size_t>(n);
            }
            ::close(fd);
        }
        {
            std::ofstream f(pub_path);
            if (!f) throw std::runtime_error("Failed to write public key");
            f << public_key_pem_;
        }

        log->info("RSA keypair generated and saved");
    }
}

std::string KeyManager::sign_token(const bsfchat::JwtClaims& claims) const {
    return bsfchat::jwt_sign(claims, private_key_pem_, key_id_);
}

nlohmann::json KeyManager::get_jwks() const {
    auto jwk = bsfchat::pem_to_jwk(public_key_pem_, key_id_);
    return nlohmann::json{{"keys", nlohmann::json::array({jwk})}};
}

} // namespace bsfchat::id
